import pool from '../config/db.js';
import { getSoftwareByManager } from '../models/softwareModel.js';
import { createSubscription } from '../models/subscriptionModel.js';
import { findUserByEmail } from '../models/userModel.js';

export const getManagerDashboard = async (req, res, next) => {
  try {
    const managerId = req.user.id;

    // Get total sales and earnings generated by this manager's assigned software
    const salesQuery = `
      SELECT 
        COALESCE(SUM(sub.amount_paid), 0) as total_earnings, 
        COUNT(sub.id) as sales_count 
      FROM subscriptions sub 
      JOIN manager_software ms ON sub.software_id = ms.software_id 
      WHERE ms.manager_id = $1
    `;
    const { rows } = await pool.query(salesQuery, [managerId]);

    // Get list of sales transactions
    const transactionsQuery = `
      SELECT 
        sub.id,
        sub.amount_paid,
        sub.plan_type,
        sub.created_at,
        u.email as client_email,
        s.name as software_name
      FROM subscriptions sub
      JOIN users u ON sub.user_id = u.id
      JOIN software s ON sub.software_id = s.id
      JOIN manager_software ms ON s.id = ms.software_id
      WHERE ms.manager_id = $1
      ORDER BY sub.created_at DESC
    `;
    const transactions = await pool.query(transactionsQuery, [managerId]);

    res.json({
      totalEarnings: parseFloat(rows[0].total_earnings || 0),
      salesCount: parseInt(rows[0].sales_count || 0),
      transactions: transactions.rows
    });
  } catch (error) {
    next(error);
  }
};

export const getAssignedSoftware = async (req, res, next) => {
  try {
    const managerId = req.user.id;
    const softwareList = await getSoftwareByManager(managerId);
    res.json(softwareList);
  } catch (error) {
    next(error);
  }
};

export const logSale = async (req, res, next) => {
  try {
    const { clientEmail, softwareId, planType, amountPaid } = req.body;

    if (!clientEmail || !softwareId || !planType || !amountPaid) {
      return res.status(400).json({ message: 'Client email, software ID, plan type, and amount paid are required.' });
    }

    const client = await findUserByEmail(clientEmail);
    if (!client) {
      return res.status(404).json({ message: 'Client email is not registered on the platform.' });
    }

    // Set end date based on plan type
    const endDate = new Date();
    if (planType === 'yearly') {
      endDate.setFullYear(endDate.getFullYear() + 1);
    } else {
      endDate.setMonth(endDate.getMonth() + 1);
    }

    const subscription = await createSubscription({
      userId: client.id,
      softwareId,
      planType,
      amountPaid,
      endDate
    });

    res.status(201).json({
      message: 'Sale logged successfully and subscription activated.',
      subscription
    });
  } catch (error) {
    next(error);
  }
};
